config/routes.rb
Rails.application.routes.draw do

  resources :boards do 
    resources :tickets
  end

  resources :tickets
  root 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true

  has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @ticket = Ticket.new
    @board = Board.find(params[:id])
    @backlog_tickets = @board.tickets.where(status: "backlog")
    @current_sprint_tickets = @board.tickets.where(status: "current sprint")
    @in_progress_tickets = @board.tickets.where(status: "in progress")
    @done_tickets = @board.tickets.where(status: "done")
  end

  def new
    @board = Board.new
  end

  def create
    board = Board.new(board_params)
    if board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  private

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    ticket = Ticket.new(ticket_params)
    if ticket.save
      redirect_to :back
    end
  end

  def update 
    receiver = params[:send]
    ticket = Ticket.find(params[:id])
    if receiver == "bl"
      ticket.status = "backlog"
    elsif receiver == "cs"
      ticket.status = "current sprint"
    elsif receiver == "ip"
      ticket.status = "in progress"
    else
      ticket.status = "done"
    end
    ticket.save
    redirect_to :back
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/boards/index.html.erb
<h1>Current Boards</h1>
<ul>
  <% @boards.each do |board| %>
    <li><%= link_to board.title, board_path(board) %></li>
  <% end %>
</ul>
<%= link_to "Create New Board", new_board_path %>

app/views/boards/new.html.erb
<h1>Please include a title for your new board</h1>

<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Submit" %>
<% end %>

app/views/boards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      Project: <%= @board.title %>
    </div>
    <div class="col-xs-8">
      <%= form_for @ticket do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <%= f.label :status %>
        <%= f.text_field :status %>
        <%= f.submit "Add New Ticket" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 statuses">
      <div class="row">
        Backlogs
      </div>
      <div class="row">
        <ul>
          <% @backlog_tickets.each do |ticket| %>
            <%= render :partial => 'shared/ticket_form', :locals =>  {:board => @board, :ticket => ticket} %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-xs-3 statuses">
      <div class="row">
        Current Sprint
      </div>
      <div class="row">
        <ul>
          <% @current_sprint_tickets.each do |ticket| %>
            <%= render :partial => 'shared/ticket_form', :locals =>  {:board => @board, :ticket => ticket} %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-xs-3 statuses">
      <div class="row">
        In Progress
      </div>
      <div class="row">
        <ul>
          <% @in_progress_tickets.each do |ticket| %>
            <%= render :partial => 'shared/ticket_form', :locals =>  {:board => @board, :ticket => ticket} %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-xs-3 statuses">
      <div class="row">
        Done
      </div>
      <div class="row">
        <ul>
          <% @done_tickets.each do |ticket| %>
            <%= render :partial => 'shared/ticket_form', :locals =>  {:board => @board, :ticket => ticket} %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TuringBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_ticket_form.html.erb
<div class="row ticket-style">
  <p>Title: <%= ticket.title %></p>
  <p>Description: <%= ticket.description %></p>
  <% if ticket.status == "backlog" %>
    <%= button_to "move to current_sprint", board_ticket_path(board.id, ticket.id, send: "cs"), method: :put %>
  <% elsif ticket.status == "current sprint" %>
    <%= button_to "move to backlog", board_ticket_path(board.id, ticket.id, send: "bl"), method: :put %>
    <%= button_to "move to in progress", board_ticket_path(board.id, ticket.id, send: "ip"), method: :put %>
  <% elsif ticket.status == "in progress" %>
    <%= button_to "move to current sprint", board_ticket_path(@board.id, ticket.id, send: "cs"), method: :put %>
    <%= button_to "move to done", board_ticket_path(board.id, ticket.id, send: "do"), method: :put %>
  <% else %>
    <%= button_to "move to in progress", board_ticket_path(board.id, ticket.id, send: "ip"), method: :put %>
  <% end %>
</div>